modules/install/controllers/DefaultController.php
<?php

class DefaultController extends Controller {

    public function beforeAction($action) {
        if (!in_array(Setting::$mode, ["install", "init"])) {
            $this->redirect(['/site/login']);
            die();
        }

        parent::beforeAction($action);

        $cs = Yii::app()->getClientScript();
        $root = Yii::app()->basePath;
        $path = str_replace([$root, "\\"], ["", "/"], $this->getViewPath());

        if (Setting::$mode != "init") {
            $path = "/plansys" . $path;
        }
        $cs->registerCssFile(Yii::app()->baseUrl . $path . '/install.css');

        return true;
    }

    public function getModuleUrl() {
        return str_replace("static", "modules/install/views/default/", $this->staticUrl(""));
    }

    public function actionIndex($msg = null) { 
        $base = explode("/", Yii::app()->baseUrl);
        if (array_pop($base) == "plansys") {
            echo "<a style='font-size: 20px;marign:0px auto;' href='" . implode("/", $base) . "'>Continue installation</a>";
            die();
        } else {
            $content = $this->renderPartial('index', ['msg' => $msg], true);
            $html = $this->renderPartial('_layout', ['content' => $content], true);
            echo $html;
        }
    }

    public function actionFinish() {
        if (isset($_GET['s'])) {
            echo Setting::$mode;
            die();
        }

        $this->renderForm('InstallFinishForm');
    }

    public function actionUser() {
        
        $model = new InstallUserForm;
        $error = false;
        $success = 'n';
        
        if (isset($_POST['InstallUserForm'])) {
            $model->attributes = $_POST['InstallUserForm'];            
            if ($model->validate()) {
                $user = User::model()->find();
                if (!is_null($user)) {
                    $user->username = $model->username;
                    $user->email = $model->email;
                    $user->password = Helper::hash($model->password);
                    $user->is_deleted = 0;
                    $status = $user->update(['username', 'password', 'is_deleted', 'email']);
                } else {
                    vdump($user);
                    die();
                }                
                Installer::createIndexFile("running");
                $this->redirect(['/install/default/finish']);
            }
        }
        
        $this->renderForm('InstallUserForm', $model, ['error' => $error, 'success' => $success]);
    }

    public function actionResetdb() {
        Installer::resetDB();
        $this->redirect(['/install/default/user']);
    }

    public function actionDb() {
        $model = new InstallDbForm();
        $model->driver = Setting::get('db.driver');

        $error = false;
        $mode = "init";

        if (isset($_POST['InstallDbForm'])) {
            $model->attributes = $_POST['InstallDbForm'];

            if ($model->validate()) {
                $error = false;
                        
                try {
                    switch ($model->driver) {
                        case "mysql":
                            $dbh = new pdo("mysql:host={$model->host};dbname={$model->dbname}", 
                                $model->username, $model->password, array(
                                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                            ));
                        break;
                        case "oci":
                            $dbh = new pdo("oci:dbname={$model->host}/{$model->dbname}", 
                                $model->username, $model->password, array(
                                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                            ));
                        break;
                    }
                } catch (PDOException $ex) {
                    $error = $ex->getMessage();
                }

                if (!$error) {
                    Setting::set('db.driver', $model->driver, false);
                    Setting::set('db.host', $model->host, false);
                    Setting::set('db.username', $model->username, false);
                    Setting::set('db.password', $model->password, false);
                    Setting::set('db.dbname', $model->dbname, false);
                    Setting::write();

                    if ($model->resetdb == "yes") {
                        Installer::createIndexFile("install");
                        $this->redirect(['/install/default/resetdb']);
                    } else {
                        Installer::createIndexFile("running");
                        $this->redirect(['/install/default/finish']);
                    }
                }
            }
        }


        $this->renderForm('InstallDbForm', $model, ['error' => $error, 'mode' => $mode]);
    }

}

modules/install/views/default/_layout.php
<!DOCTYPE HTML>
<html lang="en-US">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="<?= $this->staticUrl('/css/bootstrap.min.css'); ?>"  />
        <link rel="stylesheet" type="text/css" href="<?= $this->staticUrl('/css/non-responsive.css'); ?>"  />
        <link rel="stylesheet" type="text/css" href="<?= $this->staticUrl('/css/font-awesome.min.css'); ?>"  />
        <link rel="stylesheet" type="text/css" href="<?= $this->staticUrl('/css/main.css'); ?>"  />
        <link rel="stylesheet" type="text/css" href="<?= $this->moduleUrl . "install.css"; ?>"  />
        <title>Plansys Installer</title>
    </head>
    <body>

    <body ng-controller="MainController">
        
        <div id="content" class="no-widget">
            <?php echo $content; ?>
        </div>
    </body>
</html>

modules/install/views/default/index.php
<div class="install-pane">
    <div class="middle">
        <div class="inner">
            <div class="install-pane-head">
                <img src="<?= $this->staticUrl("/img/logo.png"); ?>" alt="Logo Plansys" width="300px;"/>
            </div>
    
            <?php if (!isset($msg)): ?>
            <table class="table table-bordered table-condensed install-check <?= !(Installer::getError()) ? '' : 'error' ?>">
                <?php foreach (Installer::getCheckList() as $group => $item): ?>
                <tr class="<?= Installer::getError($group) ? 'danger' : 'success'; ?>">
                    <td>
                        <a href="#" ><b><?= $group ?></b>
                            <div class="sub <?= Installer::getError($group) ? 'error' : ''; ?>" >
                                <table class="table table-condensed">
                                    <?php foreach ($item as $k => $i): ?>
                                        <tr class="<?= Installer::getError($group, $k) ? 'danger' : 'success'; ?>">
                                            <td><?= $i['title']; ?>

                                                <?php
                                                if (Installer::getError($group, $k)) {
                                                    echo '<pre style="margin:0px;font-size:11px;">' . Installer::getError($group, $k) . '</pre>';
                                                }
                                                ?>

                                            </td>
                                            <td class="install-status">
                                                <i class="fa <?= Installer::getError($group, $k) ? 'fa-times' : 'fa-check'; ?>"></i>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </table>
                            </div>
                        </a>
                    </td>
                    <td class="install-status">
                        <i class="fa <?= Installer::getError($group) ? 'fa-times' : 'fa-check'; ?>"></i>
                    </td>
                </tr>
            <?php endforeach; ?>
            </table>

            <?php if (!(Installer::getError())): ?>
            <div class="install-passed">
                <?= Setting::t("All Requirement Passed"); ?>
            
                <br>
                <br>
                <a href="<?= Yii::app()->controller->createUrl('/install/default/db'); ?>" class="btn btn-success">
                    <?= Setting::t("Next step"); ?> <i class="fa fa-arrow-right"></i>
                </a>
            </div>
            <?php else: ?>
            <div class="install-failed">
                <?= Setting::t("Please fix error(s) above to continue ..."); ?>
            </div>
            <?php endif; ?>
            <?php else: ?>
            <br/><br/>
            <div class="alert alert-danger install-error">
            <div class="install-error-head">
                <i class="fa fa-warning"></i> <?= Setting::t("Error while initializing plansys"); ?>
            </div>
                <?php
                echo $msg;
                ?>
                </div>
            <?php endif; ?>
        </div>
    </div>    
</div>